package gui;

import users.Doctor;
import users.Patient;
import users.User;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class ListUsers {
    private JPanel panel1;
    private JTable table1;
    private User participant;

    private static JFrame frame = new JFrame("Select a User");
    private static DefaultTableModel model = new DefaultTableModel();

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    public ListUsers(User user) {
        $$$setupUI$$$();
        model.setColumnIdentifiers(new Object[]{
                "Name, Last", "Name, First", "Username"
        });
        switch (user.getAccountType()) {
            case 2:
                Doctor doc = new Doctor(user);
                for (User p : doc.getPatients()) {
                    model.addRow(new Object[]{
                            p.getLastName(),
                            p.getFirstName(),
                            p.getUsername()
                    });
                }
                break;
            case 3:
                Patient acc = new Patient(user);
                for (User d : acc.getDoctors()) {
                    model.addRow(new Object[]{
                            d.getLastName(),
                            d.getFirstName(),
                            d.getUsername()
                    });
                }
                break;
        }

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setViewportView(table1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
