package gui;

import data.Account;
import data.Appointment;
import users.Doctor;
import users.Patient;
import users.User;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.util.LinkedList;

public class PatientConsole {
    private JPanel patientPanel;
    private JTabbedPane tabbedPane1;
    private JButton signOut;
    private JTable patApptTable;
    private JTable doctorTable;
    private JFrame frame = new JFrame("Patient Console");
    private DefaultTableModel model;
    private DefaultTableModel model2;
    private final static String[] names = {"Last", "First", "Department"};
    private final static String[] appts = {"Date", "Start", "Finish", "Doctor"};
    private Patient patientUser;
    private LinkedList<User> doctorLinkedList;

    public PatientConsole(Patient patient) {
        patientUser = patient;
        $$$setupUI$$$();
        doctorLinkedList = patient.getDoctors();
        displayDoctors(doctorLinkedList);
        displayAppointments(patient);
        frame.setContentPane(patientPanel);
        frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.pack();
        frame.setVisible(true);
        WindowListener exitListener = new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                int confirm = JOptionPane.showOptionDialog(
                        null, "Are you sure that you want to close the application?",
                        "Exit Confirmation", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
                if (confirm == 0) {
                    try {
                        Account.writeToFile();
                    } catch (Exception e3) {
                        JOptionPane.showMessageDialog(null, "Could not save to file");
                    }
                    System.exit(0);
                }
            }
        };

        frame.addWindowListener(exitListener);
        signOut.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                int confirm = JOptionPane.showOptionDialog(
                        null, "Are you sure that you want to logout?",
                        "Logout Confirmation", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
                if (confirm == 0) {
                    Login login = new Login();
                    login.init();
                    frame.dispose();
                }
            }
        });
        doctorTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int row = doctorTable.rowAtPoint(e.getPoint());
                    Doctor doctor = (Doctor) doctorLinkedList.get(row);
                    System.out.println(patient.getFirstName());
                    ScheduleView view = new ScheduleView(doctor, 0);
                    e.consume();
                }
            }
        });
    }

    private void displayAppointments(Patient patient) {
        for (Appointment a : patient.getSchedule().list) {
            Object[] toAdd = {
                    a.getStart().toLocalDate().toString(),
                    a.getStart().toLocalTime().toString(),
                    a.getFinish().toLocalTime().toString(),
                    a.getApptDoctor().getLastName() + ", " +
                            a.getApptDoctor().getFirstName()

            };
            model2.addRow(toAdd);
        }
    }

    private void displayDoctors(LinkedList<User> doctors) {
        for (User doctor : doctors) {
            Object[] toAdd = {
                    doctor.getLastName(), doctor.getFirstName(), ((Doctor) doctor).getDepartment()
            };
            model.addRow(toAdd);
        }
    }

    private void createUIComponents() {
        model = new DefaultTableModel(0, 0);
        model2 = new DefaultTableModel(0, 0);
        for (String s : names) {
            model.addColumn(s);
        }
        doctorTable = new JTable(model) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (String s : appts) {
            model2.addColumn(s);
        }
        patApptTable = new JTable(model2) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        patientPanel = new JPanel();
        patientPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        patientPanel.setMinimumSize(new Dimension(240, 267));
        patientPanel.setPreferredSize(new Dimension(804, 404));
        tabbedPane1 = new JTabbedPane();
        patientPanel.add(tabbedPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Appointments", panel1);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setViewportView(patApptTable);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Doctors", panel2);
        final JScrollPane scrollPane2 = new JScrollPane();
        panel2.add(scrollPane2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane2.setViewportView(doctorTable);
        signOut = new JButton();
        signOut.setText("Sign Out");
        patientPanel.add(signOut, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        patientPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return patientPanel;
    }
}
